# Generated by Django 4.2.5 on 2023-10-07 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('subject', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('date_hired', models.DateField()),
                ('level', models.IntegerField()),
                ('level_1_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('level_1_hours_in_person', models.DecimalField(decimal_places=2, max_digits=5)),
                ('level_2_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('level_2_hours_in_person', models.DecimalField(decimal_places=2, max_digits=5)),
                ('post_level_2_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('logged_25_hours_level_1', models.DateField()),
                ('logged_25_hours_level_2', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Takes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CertTracApp.course')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CertTracApp.tutor')),
            ],
        ),
    ]
