# Generated by Django 4.2.6 on 2023-11-16 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=40)),
                ('in_person_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('async_hours', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('level', models.IntegerField()),
                ('topic', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('date_hired', models.CharField(max_length=40)),
                ('level', models.IntegerField(default=0)),
                ('level_1_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('level_1_hours_in_person', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('logged_25_hours_level_1', models.DateField(blank=True, default=None, null=True)),
                ('level_1_completion_date', models.DateField(blank=True, default=None, null=True)),
                ('level_2_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('level_2_hours_in_person', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('post_level_2_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('level_2_completion_date', models.DateField(blank=True, default=None, null=True)),
                ('logged_25_hours_level_2', models.DateField(blank=True, default=None, null=True)),
                ('number_basic_courses_completed_level_1', models.IntegerField(default=0)),
                ('number_basic_courses_completed_level_2', models.IntegerField(default=0)),
                ('number_communication_courses_completed_level_1', models.IntegerField(default=0)),
                ('number_communication_courses_completed_level_2', models.IntegerField(default=0)),
                ('number_learningstudytechinque_courses_completed_level_1', models.IntegerField(default=0)),
                ('number_learningstudytechinque_courses_completed_level_2', models.IntegerField(default=0)),
                ('number_ethicsequality_courses_completed_level_1', models.IntegerField(default=0)),
                ('number_ethicsequality_courses_completed_level_2', models.IntegerField(default=0)),
                ('number_elective_courses_completed_level_1', models.IntegerField(default=0)),
                ('number_elective_courses_completed_level_2', models.IntegerField(default=0)),
                ('review_level_1_completed', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Takes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CertTracApp.session')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CertTracApp.tutor')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='subtopic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CertTracApp.subtopic'),
        ),
    ]
