# Generated by Django 4.2.5 on 2023-10-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CertTracApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='level_1_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='level_1_hours_in_person',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='level_2_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='level_2_hours_in_person',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='logged_25_hours_level_1',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='logged_25_hours_level_2',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='post_level_2_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
