# Generated by Django 4.2.6 on 2023-11-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CertTracApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='semester',
            field=models.TextField(),
        ),
    ]
