# Generated by Django 4.2.5 on 2023-10-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CertTracApp', '0002_alter_tutor_level_alter_tutor_level_1_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(default='', max_length=40),
        ),
    ]
