# Generated by Django 4.2.5 on 2023-10-07 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CertTracApp', '0004_alter_course_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='title',
            new_name='name',
        ),
    ]
