# Generated by Django 4.2.5 on 2023-10-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CertTracApp', '0005_rename_title_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='number_basic_courses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tutor',
            name='number_communication_courses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tutor',
            name='number_elective_courses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tutor',
            name='number_ethicsequality_courses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tutor',
            name='number_learningstudytechinque_courses',
            field=models.IntegerField(default=0),
        ),
    ]
