# Generated by Django 4.2.6 on 2023-10-26 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CertTracApp', '0006_tutor_number_basic_courses_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='number_basic_courses',
            new_name='number_basic_courses_completed',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='number_communication_courses',
            new_name='number_communication_courses_completed',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='number_elective_courses',
            new_name='number_elective_courses_completed',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='number_ethicsequality_courses',
            new_name='number_ethicsequality_courses_completed',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='number_learningstudytechinque_courses',
            new_name='number_learningstudytechinque_courses_completed',
        ),
        migrations.AddField(
            model_name='tutor',
            name='level_1_completion_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='level_2_completion_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='logged_25_hours_level_1',
            field=models.DateField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type_hours', models.CharField(max_length=40)),
                ('training_time', models.DecimalField(decimal_places=2, max_digits=5)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CertTracApp.course')),
            ],
        ),
    ]
