# Generated by Django 4.2.6 on 2023-10-27 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CertTracApp', '0008_inpersontrainingsession_totaltrainingsession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inpersontrainingsession',
            name='course',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='inpersontrainingsession',
            name='date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='totaltrainingsession',
            name='course',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='totaltrainingsession',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
