# Generated by Django 4.2.6 on 2023-10-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CertTracApp', '0009_alter_inpersontrainingsession_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takes',
            name='tutor',
        ),
        migrations.AlterField(
            model_name='takes',
            name='course',
            field=models.CharField(max_length=40),
        ),
    ]
