# Generated by Django 4.2.6 on 2023-10-27 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CertTracApp', '0011_takes_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takes',
            name='tutor',
            field=models.IntegerField(),
        ),
    ]
