# Generated by Django 4.2.6 on 2023-10-30 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CertTracApp', '0014_alter_takes_semester'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='SubTopic',
        ),
        migrations.DeleteModel(
            name='InPersonTrainingSession',
        ),
        migrations.DeleteModel(
            name='TotalTrainingSession',
        ),
        migrations.RenameField(
            model_name='subtopic',
            old_name='subject',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='takes',
            old_name='course',
            new_name='sub_topic',
        ),
    ]
