# Generated by Django 4.2.6 on 2023-10-30 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CertTracApp', '0017_rename_subtopic_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='topic',
            new_name='subject',
        ),
    ]
