# Generated by Django 4.2.6 on 2023-11-12 05:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CertTracApp', '0019_rename_sub_topic_takes_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_tutored', models.CharField(max_length=100)),
                ('hours_tutored', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_hours', to='CertTracApp.tutor')),
            ],
        ),
    ]
