# Generated by Django 4.2.6 on 2023-11-14 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CertTracApp', '0021_auto_20231112_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='Course',
            new_name='Subtopic',
        ),
        migrations.DeleteModel(
            name='InPersonTrainingSession',
        ),
        migrations.DeleteModel(
            name='TotalTrainingSession',
        ),
        migrations.RenameField(
            model_name='subtopic',
            old_name='subject',
            new_name='topic',
        ),
        migrations.RemoveField(
            model_name='takes',
            name='course',
        ),
        migrations.AddField(
            model_name='takes',
            name='subtopic',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='CertTracApp.subtopic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='review_level_1_completed',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='takes',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CertTracApp.tutor'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='level_1_completion_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='level_2_completion_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='logged_25_hours_level_1',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='logged_25_hours_level_2',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='TutorHours',
        ),
    ]
